### PR TITLE
Updated states.yml

### PR DESCRIPTION
**Pull request by satyasarathy**
Corrected empty stale name entry.

### CODE REVIEW

**Review by luisramos0 — COMMENTED** [review]
I am not sure if changing the IDs here will just break the DB, do you need to change the IDs. I think you would need to reset the database to do this.

**Comment by satyasarathy** [comment]
@luisramos0 There was an empty "name" entry, line 70, which was throwing error at the time of deployment. So, to correct that the the IDs were ordered accordingly. Plus, the India instance is pristine.

**Comment by luisramos0** [comment]
yes, i understand that, the DB is pristine but the original IDs are already on the DB. What will happen to these new IDs?

**Comment by satyasarathy** [comment]
@luisramos0 I agree, just wanted the states file to be error free. This is for any future usage of the localization files. Current setup will not be touched.

**Comment by duleorlovic** [comment]
We have started new instance and[ just removed item with blank name](https://github.com/openfoodfoundation/l10n_in/pull/3/files). I think that ids are not so important (we can keep old with missing id 17) so I think we can close this.

**Comment by duleorlovic** [comment]
Merged on https://github.com/openfoodfoundation/l10n_in/pull/3

**Pull request closed without merging**
